# Generated by Django 4.0.2 on 2022-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='tuition',
            field=models.BigIntegerField(default=29000000),
            preserve_default=False,
        ),
    ]
