# Generated by Django 4.0.2 on 2022-02-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_university_tuition'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.CharField(default="12 Istiqlol ko'chasi, Toshkent 100047", max_length=255),
            preserve_default=False,
        ),
    ]
