# Generated by Django 4.0.2 on 2022-02-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_university_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('univer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='university.university')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
